### ISSUE TITLE
Ability to hide buttons

### ISSUE THREAD

**Issue by nelsonbonet** [finity69x2/cover-position-preset-row#10]
Could it be implemented to hide any of the buttons that are not needed. Similar to the implementation you did in the Cover Button Row repository.

**Comment by finity69x2** [comment]
I'm not sure that would be feasible. The Cover Button row only hid a specific button and only in cases where the functionality wasn't available.

What buttons are you suggesting that you need/want to hide?

**Comment by nelsonbonet** [comment]
Either the first or last.  In essence, going from 4 preset values to 3 ( ie. open, mid, close).

**Comment by finity69x2** [comment]
I updated to be able to hide one of the buttons in the middle to turn it into a three position row.

try it and see if you have any issues.

EDIT:

Actually I realiozed there iks a lot more work involved to get this to work correctly so I've reversed the decision.

Sorry. I'll try to get to it soon...eventually...;)

**Comment by ManCaveMedia** [comment]
Would love to be able to choose between 3 or 4 buttons.
