### ISSUE TITLE
It's not a bug it's a feature!?

### ISSUE THREAD

**Issue by Bascht74** [finity69x2/cover-position-preset-row#11]
Hi, first of all, thanks for the great cover card for HA. 

I configured the card and have two issues: 
1. If the covers are moving, Tasmota updates the position, but the position is not reported e.g. by the color of the active button. Instead it is using the "closed" button while moving. 

while moving from 33% to 66%: 
![image](https://user-images.githubusercontent.com/66269310/107565169-aaaaca80-6be3-11eb-83e3-d9dbcb9765fb.png)

after moving: 
![image](https://user-images.githubusercontent.com/66269310/107565212-b8f8e680-6be3-11eb-9d23-73dc19988bd5.png)

I would expected it to "move" while the covers are moving...

2. I the cover is moving, there is no possibility to stop the moving cover. This could be a "stop" button or if you tab on any / the marked button while it is moving...

Both would help to get a better user experience. 
Hopefully you got some time to look into it. 
Thx in advance!

Sebastian

**Comment by finity69x2** [comment]
"I would expected it to "move" while the covers are moving..."

So would I.

So just so I understand...

when the cover is not at the 66% position and you click the button for the 66% position, the position state entity updates it's current position in real time (ex starts at 0% and continuously counts up 1%, 2%, 3%...66%) but the button actually shows the cover as "closed" until the cover reaches the 66% position?

is that correct?

as far as #2 I'm not sure how I would implement that without adding a dedicated stop button. Which I could do but...

Does your cover implement a stop command? Some don't. If not then it wouldn't do any good to include a button for it.
