### ISSUE TITLE
First button not working

### ISSUE THREAD

**Issue by flyingdutchman31** [finity69x2/cover-position-preset-row#13]
I am trying to get this to work with my solarscreen. I figured out 100% is open and 0% is closed, but somehow the first button is not clickable and is continuously colored blue.

I have attached my yaml code and screenshot of the lovelace card. Dit is specify something wrong in the yaml code?

![cover-position-preset-row](https://user-images.githubusercontent.com/912005/112746003-97de3080-8fac-11eb-8b38-6c2a855c515e.jpg)

**Comment by finity69x2** [comment]
the only thing i see right away is that you have the same setpoint for two buttons. I'm not sure I ever tested for that scenario so I don't know what the result will be.

try changing the setpoint for midclosed to 75% and see what you get.

**Comment by flyingdutchman31** [comment]
Hi thx for the quick reply. I change the settings, but still the button of closePosition is not working.


type: entities
show_header_toggle: false
state_color: false
entities:
  - type: 'custom:cover-position-preset-row'
    name: Zonnescherm
    entity: cover.tuin_zonnescherm
    reverseButtons: false
    width: 40px
    height: 35px
    customSetpoints: true
    buttonInactiveColor: '#759aaa'
    openPosition: 0
    midOpenPosition: 50
    midClosePosition: 75
    closePosition: 100
    customText: true
    customOpenText: 100%
    customMidOpenText: 50%
    customMidClosedText: Dicht75
    customClosedText: Dicht100

**Comment by finity69x2** [comment]
what is the current state of the entity in the dev tools states page?

**Comment by flyingdutchman31** [comment]
This is in closed position. Which in my case completely rolled up solar screen.

***@***.***D72488.707ECF70]


***@***.***D72488.6FDD1130]

**Comment by flyingdutchman31** [comment]
This is in closed position. Which in my case completely rolled up solar screen.
Entity: cover.tuin_zonnescherm
State: closed
current_position: 100
friendly_name: Tuin_zonnescherm
supported_features: 15
device_class: window

**Comment by finity69x2** [comment]
Sorry, it's taken so long to get back to this.

I know what's going on now. I just have to figure out how to solve it.

the custom setpoints calculation expects that the open position will be higher than the closed position with the mid positions in series in between those extremes (40 - 30 - 20 - 10 will work for open to closed but the reverse won't work).

I'll try to get to it as soon as I can.

I appreciate your patience.

**Comment by flyingdutchman31** [comment]
No problem at all. This sun isn't shining that much, so I don't use the solarscreen that often :-).  I am already glad you created the frontend and you were willing to look into my problem.

**Comment by finity69x2** [comment]
@flyingdutchman31 

Do you know how to manually import code to your HA lovelace?

I have a fix to this issue (I think...) but I don't want to do a release with the code until I have someone else test it against their real-world system. I only have a rigged up test cover since I don't actually have any real blinds.

To test this do the following:

1. go to my gist page at the link below

https://gist.github.com/finity69x2/2cc721630e7327fdb6eb652e2eb5d251

2. then download the zip file by clicking the button at the top right

3. extract that file into your "www/community/cover-position-preset-row/" directory replacing the file already existing there. You can rename the existing file to "cover-position-preset-row.js.old" if you want first so if it doesn't work you can easily restore the old file.

4. there will be another file in that folder called "cover-position-preset-row.js.gz". you will have to either delete it or rename it as well.

5. restart HA and force the browser to re-load the cache (ctrl-F5 in chrome).

6. test it out.

just be aware that the button names haven't changed and I have no idea how to do that and make it make sense. My advice would be to use the default custom text values for the buttons (which are the custom setpoint values) until you verify which buttons do what.

so set your plugin config:

```
 - type: 'custom:cover-position-preset-row'
    name: Zonnescherm
    entity: cover.tuin_zonnescherm
    reverseButtons: false
    width: 40px
    height: 35px
    customSetpoints: true
    buttonInactiveColor: '#759aaa'
    openPosition: 0
    midOpenPosition: 50
    midClosePosition: 75
    closePosition: 100
    customText: true
```

After you are satisfied with the plugin then you can set the appropriate buttons to the appropriate custom text.

let me know if you need any help.

**Comment by silversmarty** [comment]
Hi @finity69x2 , has this fix been finally added to the plugin ? I'm in the same situation ("close" button is always inactive), and it may be for the same reason (for my Zigbee module, 0 is Open and 100 is closed).

I can test it on my side if you want, but please confirm the previous how-to is still valid.

Thanks

**Comment by maxgyver87** [comment]
> Do you know how to manually import code to your HA lovelace?
> 
> I have a fix to this issue (I think...) but I don't want to do a release with the code until I have someone else test it against their real-world system. I only have a rigged up test cover since I don't actually have any real blinds.
> 
> To test this do the following:
> 
> 1. go to my gist page at the link below
> 
> https://gist.github.com/finity69x2/2cc721630e7327fdb6eb652e2eb5d251
> 
> 1. then download the zip file by clicking the button at the top right
> 2. extract that file into your "www/community/cover-position-preset-row/" directory replacing the file already existing there. You can rename the existing file to "cover-position-preset-row.js.old" if you want first so if it doesn't work you can easily restore the old file.
> 3. there will be another file in that folder called "cover-position-preset-row.js.gz". you will have to either delete it or rename it as well.
> 4. restart HA and force the browser to re-load the cache (ctrl-F5 in chrome).
> 5. test it out.
> 
> just be aware that the button names haven't changed and I have no idea how to do that and make it make sense. My advice would be to use the default custom text values for the buttons (which are the custom setpoint values) until you verify which buttons do what.
> 
> so set your plugin config:
> 
> ```
>  - type: 'custom:cover-position-preset-row'
>     name: Zonnescherm
>     entity: cover.tuin_zonnescherm
>     reverseButtons: false
>     width: 40px
>     height: 35px
>     customSetpoints: true
>     buttonInactiveColor: '#759aaa'
>     openPosition: 0
>     midOpenPosition: 50
>     midClosePosition: 75
>     closePosition: 100
>     customText: true
> ```
> 
> After you are satisfied with the plugin then you can set the appropriate buttons to the appropriate custom text.
> 
> let me know if you need any help.

@finity69x2
Just encountered the problem of the close button not working.
After applying this fix it works.
Is It possible this change is not yet included in the HACS plugin?

**Comment by flyingdutchman31** [comment]
Sorry for the late feedback. I downloaded and uploaded the code. At the moment there is some maintenance done at the wall. As soon as its clear I will test the sunscreen and will post back.

Sincere,
Christian

**Comment by flyingdutchman31** [comment]
Just tested the plugin. First button (0%) not working. Also the 99% button only opens the sunscreen for a quarter.
