### ISSUE TITLE
Presets on the same row as default controls

### ISSUE THREAD

**Issue by emilp333** [finity69x2/cover-position-preset-row#15]
Hi,

Thanks for this card! 
I'm always trying to find a better way to slim down the user interface and this card help in a way but if you want both up/down controls plus the presets you need to have two rows. What if we could have an option to have the presets on the same row as the up/down control.

What do you think? :)

**Comment by finity69x2** [comment]
I have no idea if it's possible but I kind of doubt it is.

If it is I have no idea how to do it.

But the other thing is that space for each row of the entities is always limited so I don't think I could elegantly fit everything into one row anyway.

So I doubt I would spend any time on it.

Sorry.

But there is another custom plugin that's called multiple entity row (or something like that) that you might be able to use.
