### ISSUE TITLE
Open cover if position is already 100

### ISSUE THREAD

**Issue by klatka** [finity69x2/cover-position-preset-row#16]
I have a group of covers (cover.all) that reports position 100 even when there is one cover in the group that has position 30. So the Open button is highlighted in this situation. If I click on Open nothing happens.

Is there a possibility to dont highlight the button that is showing the current position?

Then I would be able to click on open to send the service call to set position of cover.all to 100 even if cover.all is reporting position 100.

**Comment by finity69x2** [comment]
I added the ability to prevent the buttons from being disabled.

I hope this fixes your issue. Please let me know if it helps.
