### ISSUE TITLE
can I hide the name and icon?

### ISSUE THREAD

**Issue by shadowdavis** [finity69x2/cover-position-preset-row#17]
hi, can I hide the name and icon? Just these four buttons are fine

**Comment by finity69x2** [comment]
No that functionality is outside the scope of these controls and is determined by HA itself.

you might be able to use other custom plug-ins like card-mod but I've never looked into it and would have no idea how or if it could done.

**Comment by finity69x2** [comment]
No that functionality is outside the scope of these controls and is determined by HA itself.

you might be able to use other custom plug-ins like card-mod but I've never looked into it and would have no idea how or if it could done.
