### ISSUE TITLE
Not an issue but feature request

### ISSUE THREAD

**Issue by RobertoCravallo** [finity69x2/cover-position-preset-row#20]
As far as I can tell, it is either "%" or custom text. Is there a way to have custom text and show the position of the cover (32% and changing as the cover travels) in only one of the buttons? That would make this perfect!!!!

**Comment by finity69x2** [comment]
TBH, I'm not sure how that would work.

the buttons now have the setpoint displayed on the button (as you said by either text or a percent value).

I'm not sure it would make sense for one of the buttons to suddenly start changing the displayed value when you click on a button.

And how do you know if the button is displaying the desired setpoint value or the current actual position value?

I'm really disinclined to add this.

you might be able to do what you want by using another plugin (https://github.com/benct/lovelace-multiple-entity-row) and then just adding the current position value as another element in the row using that plugin.
