### ISSUE TITLE
Possibility to show only two or three buttons

### ISSUE THREAD

**Issue by iridium2001** [finity69x2/cover-position-preset-row#23]
Hello @finity69x2 , thanks for sharing this cover control.  Would be great to have the possibility to show just two or three presets. Ideally in a way that one could have them optionally on a configurable position (e.g., leave out position midOpen on one row and have it on others, to keep the alignment).
And perhaps to include a stop button as well. 

Looks like you already tried  / started to implement hiding of buttons. Would love to use this some day!

P.S: wanted to open this post as a question and not as an issue, but did not find a way to set the label.

**Comment by finity69x2** [comment]
I'll try to get time to implement it.

**Comment by iridium2001** [comment]
Hi @finity69x2 , this would be  fantastic! I'm still interested in this feature and perhaps others as well.

**Comment by Hansontech190** [comment]
Yes very interested in this as would like to show only two positions.

**Comment by finity69x2** [comment]
I've added the option. it should be available in HACS soon
