### ISSUE TITLE
Polymer deprecated in Home Assistant 2023.4 and removed in 2023.5

### ISSUE THREAD

**Issue by KennethLavrsen** [finity69x2/cover-position-preset-row#24]
per Home Assistant 2023.4.0 we get this warning when custom components use Polymer
and as I search the code for this one I see Polymer

Any chance this card gets an update before 2023.5?

**Comment by Krocko** [comment]
@finity69x2  with HA 2023.5 beta this card don‘t work anymore. 
Could you please look into it?

**Comment by finity69x2** [comment]
Should now be fixed.
