### ISSUE TITLE
Is it possible to have more position button between 0 and 100 positions ?

### ISSUE THREAD

**Issue by Tatouland** [finity69x2/cover-position-preset-row#25]
Hello

All in the tittle

Cordialy

**Comment by finity69x2** [comment]
I've found that having max of 4 buttons is the best trade-off between functionality and usability. Too many buttons and the row gets too crowded in my view.

then I would need to try to code in all of the possible number of desired buttons. Some people want 2 buttons, others want 10.

I'll have to decline the request.

Sorry
