### ISSUE TITLE
2023.5.x not working an more.

### ISSUE THREAD

**Issue by acdcnow** [finity69x2/cover-position-preset-row#26]
Since 2023.5.x cover preset is not working any more due to prerequisite change. A replacement or redesign is needed for 2023.5.x onwards.

**Comment by arboeh** [comment]
Yup, can confirm the issue.

**Comment by jpettitt** [comment]
+1

**Comment by vedette15** [comment]
+1

**Comment by cpomodoro** [comment]
+1

**Comment by peternijssen** [comment]
I'm afraid these cards are dead unless someone is capable of helping out and fixing them: https://community.home-assistant.io/t/finally-announcing-my-suite-of-lovelace-plugins/218584/63

**Comment by epytir123** [comment]
it's fixed in the new version :)

**Comment by finity69x2** [comment]
Yes, fixed now.
