### ISSUE TITLE
Not working with Attributes

### ISSUE THREAD

**Issue by thomasknuchel** [finity69x2/cover-position-preset-row#28]
My new cover entities have tilt as an attribute and not as a separate entity. 

type: custom:cover-position-preset-rowentity:
cover.office_blinds_east
attribute: tilt

Attribute is getting ignored and main cover is used only. Could also be a user error :) Please advice.

**Comment by finity69x2** [comment]
Yes, the card only uses the set cover position on the main entity and doesn't use the tilt attribute.

I don't have any covers with tilt attributes so I can't really implement and test things since I don't even know how those covers work.
