### ISSUE TITLE
[SOLVED] Feature Request: Only show Custom position

### ISSUE THREAD

**Issue by woody4165** [finity69x2/cover-position-preset-row#6]
Hi

would it be possible to show only Custom position?

Thanks

**Comment by finity69x2** [comment]
I'm not sure what you mean. Could you give examples?

**Comment by woody4165** [comment]
> I'm not sure what you mean. Could you give examples?

I mean only the custom position row and not also the row with up, down and stop button.

Thanks

**Comment by finity69x2** [comment]
can you show me the config for your card? And a screenshot of what you are seeing on the card?

**Comment by woody4165** [comment]
@finity69x2 
MY FAULT!!

All is working, I haven't tried the card until nw, but seeing the code and cards in the examples, I thought that this card was showing all the elements...
