### ISSUE TITLE
Using input_number for values

### ISSUE THREAD

**Issue by mgriffin13** [finity69x2/cover-position-preset-row#8]
Would it be possible to use an `input_number` for the `midOpenPosition` and `midClosePosition` values? I have my positions set via `input_number` so I can use them in automations and scripts, and I would like to just reference those values rather than statically setting them.

**Comment by finity69x2** [comment]
You can't do that directly with this control row but you could likely use other custom cards to interact with this to accomplish what you want.

Something like "lovelace card templater" might work but I've never tried it.
