### ISSUE TITLE
Arrows and stop button not visible

### ISSUE THREAD

**Issue by MobiD2017** [finity69x2/cover-position-preset-row#9]
In to the card the up, down and stop butten are not visible.
Buttons for direct possitions are working fine.

My Config is:
      - type: entities
        title: Rolladen
        show_header_toggle: false
        state_color: true
        entities:
          - type: 'custom:cover-position-preset-row'
            name: Terrasentür
            entity: cover.Stube
            reverseButtons: true
            customTheme: true
            isOpenColor: 'rgb(255, 0, 0)'
            isMidOpenColor: '#888888'
            isMidClosedColor: '#222222'
            isClosedColor: purple
            buttonInactiveColor: black
            customSetpoints: true
            openPosition: 1
            midOpenPosition: 0.5
            midClosePosition: 0.35
            closePosition: 0
            customText: true
            customOpenText: Auf
            customMidOpenText: 50%
            customMidClosedText: 35%
            customClosedText: Zu

Can you help me for this?

**Comment by finity69x2** [comment]
It's hard to tell exactly what you are talking about but I think you are describing the way the card is supposed to work.

This row is a replacement for the built-in row controls and will only show the buttons for each position. The arrows aren't included here intentionally. If you want both you can use the same cover entity with my control row and get the buttons and use the same entity above or below without my control row and you can have the up/down arrows too. Just not on the same row.
